version: '3'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bts
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin      
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: